name: CD

on:
  push:
    tags:
    - '*'

jobs:
  build-lin:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-10-multilib
    - name: Build
      run: |
        export RELEASE_BUILD=1
        make
    - name: Create Artifact
      uses: actions/upload-artifact@v2
      with:
        name: krzymod-linux
        path: krzymod.so
  build-win:
    name: Windows Build
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      env:
        RELEASE_BUILD: 1
      run: |
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\KrzyMod.sln /t:KrzyMod /p:Configuration=Release /p:Platform=x86
    - name: Create Artifact
      uses: actions/upload-artifact@v2
      with:
        name: krzymod-windows
        path: bin/krzymod.dll
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.repository == 'Krzyhau/KrzyMod'
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    needs:
    - build-lin
    - build-win
    steps:
    - name: Get Release Version
      id: get_release
      run: echo ::set-output name=version::${GITHUB_REF:10}
    - name: Download Linux Build
      uses: actions/download-artifact@v2
      with:
        name: krzymod-linux
    - name: Download Windows Build
      uses: actions/download-artifact@v2
      with:
        name: krzymod-windows
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        body: |
          ![CD](https://github.com/Krzyhau/KrzyMod/workflows/CD/badge.svg)

          **Installation**
          - Download:
            - [Windows](https://github.com/Krzyhau/KrzyMod/releases/download/${{ steps.get_release.outputs.version }}/krzymod.dll)
            - [Linux](https://github.com/Krzyhau/KrzyMod/releases/download/${{ steps.get_release.outputs.version }}/krzymod.so)
          - Place the binary into the game folder e.g. `Portal 2`
          - Open developer console and enter `plugin_load krzymod`

          ---

          **Changelog**
          TODO
        draft: false
        files: |
          krzymod.so
          krzymod.dll
        prerelease: ${{ contains(github.ref, '-pre') }}
